# Generated by Django 4.2.7 on 2023-12-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatsTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_time", models.TextField()),
                ("mando_de_campo", models.TextField()),
                ("gols_marcados", models.IntegerField(default=0)),
                ("gols_sofridos", models.IntegerField(default=0)),
                ("vitorias", models.IntegerField(default=0)),
                ("derrotas", models.IntegerField(default=0)),
                ("empates", models.IntegerField(default=0)),
                ("pontos", models.IntegerField(default=0)),
                ("saldo_de_gols", models.IntegerField(default=0)),
                ("num_jogos", models.IntegerField(default=0)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EstadosBrasil",
            fields=[
                (
                    "UF",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                ("bid", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.TextField()),
                ("idade", models.IntegerField()),
                ("posicao", models.TextField(default="0")),
                ("numero_camisa", models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                ("N_Jogo", models.IntegerField(primary_key=True, serialize=False)),
                ("estadio", models.TextField()),
                ("time_visitante", models.TextField()),
                ("time_mandante", models.TextField()),
                ("placar_visitante", models.IntegerField()),
                ("placar_mandante", models.IntegerField()),
                ("N_rodada", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("nome_time", models.TextField(primary_key=True, serialize=False)),
                ("serie", models.CharField(max_length=1)),
                ("tecnico", models.TextField(default="", unique=True)),
                (
                    "UF",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todos.estadosbrasil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Substituicoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N_Jogo", models.IntegerField()),
                ("jogador_saiu", models.IntegerField()),
                ("jogador_entrou", models.IntegerField()),
                ("minuto", models.IntegerField()),
                ("segundo", models.IntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todos.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatsJogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_time", models.TextField()),
                ("N_Jogo", models.IntegerField()),
                ("cartao_amarelo", models.IntegerField(default=0)),
                ("cartao_vermelho", models.IntegerField(default=0)),
                ("impedimentos", models.IntegerField(default=0)),
                ("escanteios", models.IntegerField(default=0)),
                ("faltas", models.IntegerField(default=0)),
                ("passes", models.IntegerField(default=0)),
                ("chutes", models.IntegerField(default=0)),
                ("chutes_a_gol", models.IntegerField(default=0)),
                ("posse_de_bola", models.IntegerField(default=0)),
                ("precisao_do_passe", models.IntegerField(default=0)),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_jogo",
                        to="todos.jogo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatsJogador",
            fields=[
                ("bid", models.IntegerField(primary_key=True, serialize=False)),
                ("faltas_sofridas", models.IntegerField(default=0)),
                ("faltas_feitas", models.IntegerField(default=0)),
                ("numero_de_gols", models.IntegerField(default=0)),
                ("amarelos", models.IntegerField(default=0)),
                ("vermelhos", models.IntegerField(default=0)),
                ("numero_de_assistencias", models.IntegerField(default=0)),
                (
                    "jogador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="todos.jogador"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jogador",
            name="nome_time",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="todos.team"
            ),
        ),
        migrations.CreateModel(
            name="Gols",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N_Jogo", models.IntegerField()),
                ("jogador_marcou", models.IntegerField()),
                ("jogador_assistencia", models.IntegerField()),
                ("minuto", models.IntegerField()),
                ("segundo", models.IntegerField(default=0)),
                (
                    "time_marcou",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gols_marcou",
                        to="todos.team",
                    ),
                ),
                (
                    "time_sofreu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gols_sofreu",
                        to="todos.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faltas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("N_Jogo", models.IntegerField()),
                ("jogador_recebeu", models.IntegerField()),
                ("jogador_marcou", models.IntegerField()),
                ("minuto", models.IntegerField()),
                ("segundo", models.IntegerField(default=0)),
                (
                    "time_marcou",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faltas_marcou",
                        to="todos.team",
                    ),
                ),
                (
                    "time_sofreu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faltas_sofreu",
                        to="todos.team",
                    ),
                ),
            ],
        ),
    ]
